### ISSUE TITLE
[feat] 홈화면 구현

### ISSUE THREAD

**Issue by hongseekim** [SOPT-all/35-COLLABORATION-iOS-CGV#10]
## 📝 작업 페이지 캡쳐
|    페이지    |   캡쳐   |
| :-------------: | :----------: |
| 피그마 (1) | <img src = "https://github.com/user-attachments/assets/5a3c461a-7299-4ff2-979b-d92efc13f91a" width ="250">
| 피그마 (2) | <img src = "https://github.com/user-attachments/assets/1e1b53a6-b598-478a-b0da-a86f30a7ad84" width ="250">
| 피그마 (3) | <img src = "https://github.com/user-attachments/assets/3112f042-4da5-42fc-82f4-4b9f7fdb6a41" width ="250">

## 작업할 브랜치
- `feat#10-homeScreen` 브랜치에서 작업합니다.

## ✔️ To-Do
- [ ] 홈 화면 Compositional Layout 세팅
- [ ] 헤더 구현
- [ ] 탭바 구현
- [ ] 배너 구현
- [ ] 무비차트 구현
- [ ] 특별관 구현
- [ ] 나의 CGV 구현
- [ ] 오늘의 CGV 구현
- [ ] 푸터 구현
