### ISSUE TITLE
[feat] 시간 선택 뷰

### ISSUE THREAD

**Issue by ChoiAnYong** [SOPT-all/35-COLLABORATION-iOS-CGV#18]
## 📝 작업 페이지 캡쳐

|    페이지    |   캡쳐   |
| :-------------: | :----------: |
| 피그마 | <img src = "https://github.com/user-attachments/assets/e2a6ca72-d3b2-4ef1-9ae3-1ad20d7b12e7" width ="250"> 

## 작업할 브랜치
- `` 브랜치에서 작업합니다.

## ✔️ To-Do
- [x] 네비게이션 바 지우기
- [x] UIkit에 SwiftUI 연결
- [x]  상단 그라데이션 배경 구현
- [x] 상영작 상단 헤더 구현
- [x] 상영작 가로 스크롤뷰 구현
- [x] 날짜 헤더 구현
- [x] 날짜뷰 구현
- [x] 선택된 극장, 극장 선택, 필터가 들어갈 헤더 구현
- [x] empty뷰 구현
- [x] 극장별 상영 정보 뷰 구현
