### ISSUE TITLE
[setting] Extension 및 Base 파일 추가

### ISSUE THREAD

**Issue by mmaybei** [SOPT-all/35-COLLABORATION-iOS-CGV#3]
## 작업할 브랜치
- `setting/#3-extensionBase` 브랜치에서 작업합니다.

## ✔️ To-Do
- [x] Extension 코드 추가
- [x] Util 코드 추가
- [x] 폰트 스타일 가이드 반영
- [x] 그라디언트 스타일 가이드 반영
- [x] Base 파일 추가
